### ISSUE TITLE
Fix federal codes file download

### ISSUE THREAD

**Issue by jungshadow** [waldoj/FIPS-to-GNIS#4]
Hi @waldoj! When I saw you post about this project a few years back, I never forgot about it because I loved the idea. I'm hoping to put a bit of time into it as it as a static file API with this data could be generally useful to our work.

In trying to run it, I noticed that the download link in [`get_file.sh`](https://github.com/waldoj/FIPS-to-GNIS/blob/7bba900da5c2797afa9eb00850d910fd3d1e7c9a/bin/get_file.sh#L4) needs to be updated to reflect the new website structure. The new download link is on [this page](https://www.usgs.gov/core-science-systems/ngp/board-on-geographic-names/download-gnis-data). I have a pull request ready to go for the fix—and the result of updating the file—if you're interested and still using/updating this.

**Comment by waldoj** [comment]
Heck yeah, that'd be great!

**Comment by waldoj** [comment]
(I last had to deploy the site three years ago, and it's quietly run on S3 ever since, so I haven't had a chance to discover this problem!)
